# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hello_Nadir  
email: nadirlatif532@gmail.com
description: "Welcome to my little space on the internet. Here we talk about every thing from Game-dev to Machine/Deep Learning (What?)
Hope you find what you're looking for."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: #
github_username:  nadirlatif532
facebook_username: nadir.lateef
linkedin_username: nadirlatif532
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate,jemoji, kramdown]
# Build settings
markdown: kramdown
